name: ScreenshotCleaner
options:
  bundleIdPrefix: com.ymzuiku
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"

packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: "5.7.0"

settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  ScreenshotCleaner:
    type: application
    platform: iOS
    sources:
      - ScreenshotCleaner/Sources
      - ScreenshotCleaner/Resources
    dependencies:
      - package: SnapKit
    settings:
      base:
        INFOPLIST_FILE: ScreenshotCleaner/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.ymzuiku.ScreenshotCleaner
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: QUKNH2D57C
    postCompileScripts: []
